#!/usr/bin/env python3

import argparse
import cmd
import subprocess


class Shell(cmd.Cmd):
    intro = 'This shell allows you to run the `zfs` command. Read its man page.'
    prompt = 'zfs-manage-shell$ '

    def do_zfs(self, arg):
        status = subprocess.call(["zfs"] + arg.split(), shell=False)
        if status != 0:
            print(' -- Exit status:', status)

    def do_EOF(self, arg):
        print('exit')
        return True

    def default(self, arg):
        print('Permission denied: only `zfs` command is allowed!')

parser = argparse.ArgumentParser()

parser.add_argument('-c', '--command',
                    help='Command to be executed, starts interactive shell if ommited')

args = parser.parse_args()

if args.command is not None:
    Shell().onecmd(args.command)
else:
    Shell().cmdloop()
