#!/bin/sh

# Execute command properly. For what that means, please read the last
# section of this scirpt.

### READ CONFIG ################################################################

CONFIG='/usr/local/etc/properly.conf'
. $CONFIG

### ARGUMENTS PARSING ##########################################################

usage() {
	echo "Usage: $0 [-t title] [-s slug] command [arguments...]"
	exit 1
}

parse_args() {
	# Parses arguments and removes properly-specific arguments from argument
	# list, so that other arguments may be passed to command being executed
	while getopts "s:t:" opt; do
		case ${opt} in
			t)
				title=${OPTARG}
				;;
			s)
				slug=${OPTARG}
				;;
		esac
	done
	shift $(( ${OPTIND} - 1 )) # TODO: odprasit
	command="$@"
	[ -z "${command}" ] && usage
	if [ -z "${title}" ]; then
		title="$(to_title ${command})"
		readonly title
	fi
	if [ -z "${slug}" ]; then
		slug="$(to_slug ${title})"
		readonly slug
	fi
}

to_title() {
	date "+$* %Y/%m/%d"
}

to_slug() {
	echo "$@" | tr ' /\t' '---'
}

### HELPER FUNCTIONS ###########################################################

STDOUT_PREFIX=' * '
STDOUT_COMPLAIN_PREFIX='!!!'

complain() {
	echo "${STDOUT_COMPLAIN_PREFIX} $@"
	read -p "${STDOUT_COMPLAIN_PREFIX}     Type \"yes\" to continue (on your own responsibility): " REPLY
	if [ x"${REPLY}" != x'yes' ]; then
		msg 'Aborted.'
		exit 47
	fi
}

msg() {
	echo "${STDOUT_PREFIX}$@"
}

ask() {
	read -p "${STDOUT_PREFIX}$@ [Y/n] " REPLY
	[ x"${REPLY}" = x -o x"${REPLY}" = x"Y" -o x"${REPLY}" = x"y" ]
}

execute() {
	${command} || msg "(exit status: $?)"
}

### CHECKS AND ACTIONS #########################################################

dirty_config_dirs() {
	# Returns all config dirs with uncommitted changes, if any.
	local dirty=""
	for dir in ${etcundergit_dirs}; do
		( cd ${dir} && [ -z "$(git status --porcelain)" ] ) || dirty="${dirty} ${dir}"
	done
	echo ${dirty}
}

check_config_clean() {
	# Check and inform user that config dirs are dirty o that autocommit won't
	# mess things up
	local dirty_dirs="$(dirty_config_dirs)"
	for d in ${dirty_dirs}; do
		msg "${d} is dirty"
	done
	[ -z "${dirty_dirs}" ]
}

commit_config() {
	local commit_message="$1"
	local tag_name="$2"
	for d in $(dirty_config_dirs); do
		(
			cd ${d}
			run_git add --all .
			# empty commit just prints a message
			run_git commit -m "${commit_message} [autocommit]" && run_git tag "${tag_name}"
		)
	done
}

do_snapshot() {
	msg "creating snapshot: ${snapshot}"
	run_zfs_snapshot ${snapshot_subvol} ${1}
}

log() {
	# TODO this is a placeholder. Call real logger here.
	# $1 is title, $2 is slug, $3 is the command that was used
}

### "PROPERLY" SEQUENCE ########################################################

properly() {
	# Executing $command properly means:
	msg '=== 0) check if config directories (such as /etc) are clean =============='
	check_config_clean || complain 'Uncommitted config changes!'
	msg '=== 1) snapshot =========================================================='
	do_snapshot "pre-${slug}" || complain "Cannot create snapshot (exit code $?)!"
	msg '=== execute command ======================================================'
	execute "${command}"
	msg '=== n-2) commit config changes ==========================================='
	ask 'Autocommit config changes?' && commit_config "${title}" "${slug}"
	msg '=== n-1) snapshot ========================================================'
	do_snapshot "post-${slug}" || msg "Couldn't create snapshot (exit code $?)!"
	msg '=== n) log the change ===================================================='
	log "${title}" "${slug}" "${command}"
	msg 'Done. Check setup log and commit it when you are done.'
}

### MAIN #######################################################################

main() {
	parse_args "$@"
	properly
}

main "$@"
