#!/bin/sh

echo THIS SCRIPT IS A MESS AND NEEDS CLEANUP AND IS ONLY HERE IN HOPE THAT IT WILL BE FIXED. DO NOT USE THIS!!!

### CONFIG #####################################################################
# this should be moved to something like /usr/local/etc/properly.conf

# Subvolume to recurively snapshot
snapshot_subvol="zroot/ROOT"

# Config directories under git
etcundergit_dirs="/etc /usr/local/etc"

# Git executable to use (for custom git wrappers)
run_git() {
	mgit $@
}

# Techwiki location (for setup logs)
techwiki_location="/root/techwiki"

# Setup log location (for this particular server / jail)
techwiki_setup_log="servers/inteligent/setup.md"

### READ CONFIG -- DEAD NOW ####################################################

#CONFIG='/usr/local/etc/defaults/properly.conf'
## pull in config
#. $CONFIG
#for f in $local_config_files; do
#	. $f
#done

### ARGUMENTS PARSING ##########################################################

usage() {
	echo "Usage: $0 [-t title] [-s slug] command [arguments...]"
	exit 1
}

parse_args() {
	while getopts "s:t:" opt; do
		case ${opt} in
			t)
				title=${OPTARG}
				;;
			s)
				slug=${OPTARG}
				;;
		esac
	done
	shift $(( ${OPTIND} - 1 )) # TODO: odprasit
	command="$@"
	[ -z "$command" ] && usage
	[ -z "$title" ] && title="$(to_title $command)"
	[ -z "$slug" ] && slug="$(to_slug $title)"
}

to_title() {
	date "+$* %Y/%m/%d"
}

to_slug() {
	echo $@ | tr ' /\t' '---'
}

### HELPER FUNCTIONS ###########################################################

STDOUT_PREFIX=' * '
STDOUT_COMPLAIN_PREFIX='!!!'

complain() {
	echo "${STDOUT_COMPLAIN_PREFIX} $@"
	read -p "${STDOUT_COMPLAIN_PREFIX}     Type \"yes\" to continue (on your own responsibility): " REPLY
	if [ x"$REPLY" != x'yes' ]; then
		msg 'Aborted.'
		exit 47
	fi
}

msg() {
	echo "${STDOUT_PREFIX}$@"
}

ask() {
	read -p "${STDOUT_PREFIX}$@ [Y/n] " REPLY
	[ x"$REPLY" = x -o x"$REPLY" = x"Y" -o x"$REPLY" = x"y" ]
}

execute() {
	$command || msg "(exit status: $?)"
}

### CHECKS AND ACTIONS #########################################################

dirty_config_dirs() {
	dirty=""
	for dir in $etcundergit_dirs; do
		( cd $dir && [ ! -z "$(git status --porcelain)" ] ) | grep -q "working directory clean" \
			|| dirty="$dirty $dir"
	done
	echo $dirty
}

check_config_clean() {
	dirty_dirs="$(dirty_config_dirs)"
	for d in $dirty_dirs; do
		msg "$d is dirty"
	done
	[ -z "$dirty_dirs" ]
}

commit_config() {
	title="$1"
	slug="$2"
	for d in $(dirty_config_dirs); do
		(
			cd $d
			run_git add --all .
			# empty commit just prints a message
			run_git commit -m "$title [autocommit]" && run_git tag "$slug"
		)
	done
}

do_snapshot() {
	snapshot="${snapshot_subvol}@${1}"
	msg "creating snapshot: $snapshot"
	zfs snapshot -r "$snapshot"
}

log() {
	msg "[log] $(date +%Y-%m-%d) $1: \`$3\` <$2>"
}

### "PROPERLY" SEQUENCE ########################################################

parse_args $@

# Executing $command properly means:
msg '=== 0) check if config directories (such as /etc) are clean =============='
check_config_clean || complain 'Uncommitted config changes!'
msg '=== 1) snapshot =========================================================='
do_snapshot "pre-$slug" || complain "Cannot create snapshot (exit code $?)!"
msg '=== execute command ======================================================'
execute "$command"
msg '=== n-2) commit config changes ==========================================='
ask 'Autocommit config changes?' && commit_config "$title" "$slug"
msg '=== n-1) snapshot ========================================================'
do_snapshot "post-$slug" || msg "Couldn't create snapshot (exit code $?)!"
msg '=== n) log the change ===================================================='
log "$title" "$slug" "$command"
