#!/bin/sh
#
# Print a warning message using wall or send it via email if /etc contains
# uncommited changes.

BASE_DIR="/etc"

DATA_DIR="/var/tmp/etc-dirty-checker"

RUN_FILE="${DATA_DIR}/run"
USERS_FILE="${DATA_DIR}/users"

WALL_AFTER=10
MAIL_AFTER=45

mkdir -p "${DATA_DIR}" || exit 1

if [ ! -f "${RUN_FILE}" ]; then
  touch "${RUN_FILE}" || exit 1

  echo 0 > "${RUN_FILE}"
fi

if [ ! -f "${USERS_FILE}" ]; then
  touch "${USERS_FILE}" || exit 1
fi

cd "${BASE_DIR}"

if [ ! -z "$(git status --porcelain)" ]; then
  run="$(cat "${RUN_FILE}")"

  if [ "${run}" -eq "0" ]; then
    echo "$(who | cut -d ' ' -f 1 | sort -u)" > "${USERS_FILE}"
  fi

  run="$(expr "${run}" + 1)"

  echo "${run}" > "${RUN_FILE}"

  if [ "$(expr "${run}" % "${WALL_AFTER}")" -eq "0" ]; then
    # DO NOT REMOVE THE TABS! We need them to make the here document working.
    wall <<-END
	Warning: uncommited changes detected in ${BASE_DIR}. Please clean up!
	END
  fi

  if [ "$(expr "${run}" % "${MAIL_AFTER}")" -eq "0" ]; then
    # Send mail
  fi
else
  echo 0 > "${RUN_FILE}"
  echo -n > "${USERS_FILE}"
fi
